// Greeting cards data for v2
// Category metadata + card data

export interface GreetingCardData {
  id: string;
  title: string;
  byline: string;
  tags: string[];
  likes: number;
  cta: string;
  paperImage: string;
  /** Optional pre-made back-of-card image (shown on flip instead of user message) */
  backImage?: string;
  overlayImage: string;
  brandIcon: string;
  tapeText: string;
  description?: string;
  price: string;
}

export interface CategoryMeta {
  key: string;
  label: string;
  emoji: string;
}

export interface CategoryData {
  title: string;
  subtitle: string;
  cards: GreetingCardData[];
}

// Category pill metadata (order matches design — Miggles first)
export const categoryMeta: CategoryMeta[] = [
  { key: "miggles", label: "Miggles", emoji: "🐱" },
  { key: "base", label: "Base", emoji: "🟦" },
  { key: "degen", label: "Degen", emoji: "✨" },
  { key: "birthday", label: "Birthdays", emoji: "🎂" },
  { key: "love", label: "Love", emoji: "💗" },
  { key: "friendship", label: "Friends", emoji: "🤝" },
  { key: "congrats", label: "Congrats", emoji: "🎉" },
  { key: "thanks", label: "Thanks", emoji: "🙏" },
  { key: "sorry", label: "Sorry", emoji: "💐" },
  { key: "situation", label: "Situationship", emoji: "💭" },
  { key: "motivational", label: "Motivation", emoji: "💪" },
  { key: "work", label: "Work", emoji: "💼" },
];

export const greetingCardsData: Record<string, CategoryData> = {
  miggles: {
    title: "Miggles Cards",
    subtitle: "Send some Miggles love to your frens.",
    cards: [
      {
        id: "miggles-1",
        title: "Miggles Magic",
        byline: "by Everlink",
        tags: ["#miggles", "#cat"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/miggles/miggles1.png",
        backImage: "/images/categories/miggles/miggles2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/meep.png",
        tapeText: "MIGGLES!",
        description: "Miggles magic for your fren",
        price: "0.02 ETH",
      },
    ],
  },

  birthday: {
    title: "Birthday Cards",
    subtitle: "Celebrate special moments with personalized birthday greetings.",
    cards: [
      {
        id: "birthday-1",
        title: "Birthday Bling",
        byline: "by Everlink",
        tags: ["#birthday", "#celebration"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/birthday/HappyBirthday7.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/birthday.svg",
        tapeText: "HAPPY BIRTHDAY!!",
        description: "A delightful birthday celebration card",
        price: "0.02 ETH",
      },
      {
        id: "birthday-2",
        title: "Birthday Wishes",
        byline: "by Everlink",
        tags: ["#birthday", "#cake"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/birthday/birthday1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/birthday.svg",
        tapeText: "MAKE A WISH!",
        description: "Sweet birthday wishes with cake",
        price: "0.02 ETH",
      },
      {
        id: "birthday-3",
        title: "Party Time",
        byline: "by Everlink",
        tags: ["#birthday", "#party"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/birthday/birthday2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/birthday.svg",
        tapeText: "PARTY TIME!",
        description: "Let's celebrate in style",
        price: "0.02 ETH",
      },
      {
        id: "birthday-4",
        title: "Birthday Bash",
        byline: "by Everlink",
        tags: ["#birthday", "#party"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/birthday/bIirthday3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/birthday.svg",
        tapeText: "PARTY TIME!",
        description: "Let's celebrate in style",
        price: "0.02 ETH",
      },
    ],
  },

  congrats: {
    title: "Congratulations Cards",
    subtitle: "Celebrate achievements and milestones with style.",
    cards: [
      {
        id: "congrats-1",
        title: "Congratulations",
        byline: "by Everlink",
        tags: ["#congrats", "#achievement"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/congrats/congrats1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/congrats.svg",
        tapeText: "CONGRATS!!",
        description: "Celebrate your success",
        price: "0.02 ETH",
      },
      {
        id: "congrats-2",
        title: "Well Done",
        byline: "by Everlink",
        tags: ["#congrats", "#success"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/congrats/congrats2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/congrats.svg",
        tapeText: "WELL DONE!",
        description: "Outstanding work deserves recognition",
        price: "0.02 ETH",
      },
    ],
  },

  love: {
    title: "Love & Romance",
    subtitle: "Express your feelings with heartfelt cards.",
    cards: [
      {
        id: "love-1",
        title: "Love You",
        byline: "by Everlink",
        tags: ["#love", "#romance"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "I LOVE YOU!",
        description: "Express your deepest feelings",
        price: "0.02 ETH",
      },
      {
        id: "love-2",
        title: "Sweet Dreams",
        byline: "by Everlink",
        tags: ["#love", "#sweet"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "SWEET DREAMS",
        description: "Dreamy love messages",
        price: "0.02 ETH",
      },
      {
        id: "love-3",
        title: "Forever Yours",
        byline: "by Everlink",
        tags: ["#love", "#forever"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "FOREVER YOURS",
        description: "Eternal love and commitment",
        price: "0.02 ETH",
      },
      {
        id: "love-4",
        title: "Love Letter",
        byline: "by Everlink",
        tags: ["#love", "#letter"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love4.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "LOVE LETTER",
        description: "A heartfelt love letter",
        price: "0.02 ETH",
      },
      {
        id: "love-5",
        title: "My Heart",
        byline: "by Everlink",
        tags: ["#love", "#heart"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love5.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "MY HEART",
        description: "You have my heart",
        price: "0.02 ETH",
      },
      {
        id: "love-6",
        title: "Soulmate",
        byline: "by Everlink",
        tags: ["#love", "#soulmate"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love6.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "SOULMATE",
        description: "Found my soulmate",
        price: "0.02 ETH",
      },
      {
        id: "love-7",
        title: "Be Mine",
        byline: "by Everlink",
        tags: ["#love", "#valentine"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love7.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "BE MINE",
        description: "Will you be mine?",
        price: "0.02 ETH",
      },
      {
        id: "love-8",
        title: "Together",
        byline: "by Everlink",
        tags: ["#love", "#together"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love8.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "TOGETHER",
        description: "Better together",
        price: "0.02 ETH",
      },
      {
        id: "love-9",
        title: "Kiss",
        byline: "by Everlink",
        tags: ["#love", "#kiss"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love9.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "XOXO",
        description: "Kisses and hugs",
        price: "0.02 ETH",
      },
      {
        id: "love-10",
        title: "Endless Love",
        byline: "by Everlink",
        tags: ["#love", "#endless"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/love/love10.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/love.svg",
        tapeText: "ENDLESS LOVE",
        description: "Love without end",
        price: "0.02 ETH",
      },
    ],
  },

  work: {
    title: "Professional Cards",
    subtitle: "Business and work-related greetings.",
    cards: [
      {
        id: "work-1",
        title: "Good Work",
        byline: "by Everlink",
        tags: ["#work", "#professional"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/work/work1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/work.svg",
        tapeText: "GOOD WORK!",
        description: "Professional achievement recognition",
        price: "0.02 ETH",
      },
      {
        id: "work-2",
        title: "Team Player",
        byline: "by Everlink",
        tags: ["#work", "#team"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/work/work2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/work.svg",
        tapeText: "TEAM PLAYER!",
        description: "Celebrate teamwork",
        price: "0.02 ETH",
      },
      {
        id: "work-3",
        title: "Promotion",
        byline: "by Everlink",
        tags: ["#work", "#promotion"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/work/work3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/work.svg",
        tapeText: "PROMOTION!",
        description: "Congratulations on your promotion",
        price: "0.02 ETH",
      },
      {
        id: "work-4",
        title: "Boss Move",
        byline: "by Everlink",
        tags: ["#work", "#boss"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/work/work4.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/work.svg",
        tapeText: "BOSS MOVE!",
        description: "That was a boss move",
        price: "0.02 ETH",
      },
    ],
  },

  thanks: {
    title: "Thank You Cards",
    subtitle: "Show gratitude and appreciation.",
    cards: [
      {
        id: "thanks-1",
        title: "Thank You",
        byline: "by Everlink",
        tags: ["#thanks", "#gratitude"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/thankyou/thankyou1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/thanks.svg",
        tapeText: "THANK YOU!",
        description: "Express heartfelt gratitude",
        price: "0.02 ETH",
      },
      {
        id: "thanks-2",
        title: "Appreciated",
        byline: "by Everlink",
        tags: ["#thanks", "#appreciation"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/thankyou/thankyou2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/thanks.svg",
        tapeText: "MUCH APPRECIATED",
        description: "Show your appreciation",
        price: "0.02 ETH",
      },
      {
        id: "thanks-3",
        title: "Grateful",
        byline: "by Everlink",
        tags: ["#thanks", "#grateful"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/thankyou/thankyou3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/thanks.svg",
        tapeText: "SO GRATEFUL",
        description: "Feeling grateful",
        price: "0.02 ETH",
      },
      {
        id: "thanks-4",
        title: "Thanks a Bunch",
        byline: "by Everlink",
        tags: ["#thanks", "#bunch"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/thankyou/thankyou4.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/thanks.svg",
        tapeText: "THANKS A BUNCH",
        description: "Thanks a million",
        price: "0.02 ETH",
      },
      {
        id: "thanks-5",
        title: "You Rock",
        byline: "by Everlink",
        tags: ["#thanks", "#rock"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/thankyou/thankyou5.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/thanks.svg",
        tapeText: "YOU ROCK!",
        description: "You absolutely rock",
        price: "0.02 ETH",
      },
      {
        id: "thanks-6",
        title: "Big Thanks",
        byline: "by Everlink",
        tags: ["#thanks", "#big"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/thankyou/thankyou6.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/thanks.svg",
        tapeText: "BIG THANKS",
        description: "A big thank you",
        price: "0.02 ETH",
      },
      {
        id: "thanks-7",
        title: "Thankful",
        byline: "by Everlink",
        tags: ["#thanks", "#thankful"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/thankyou/thankyou7.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/thanks.svg",
        tapeText: "THANKFUL",
        description: "Feeling thankful",
        price: "0.02 ETH",
      },
      {
        id: "thanks-8",
        title: "Cheers",
        byline: "by Everlink",
        tags: ["#thanks", "#cheers"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/thankyou/thankyou8.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/thanks.svg",
        tapeText: "CHEERS!",
        description: "Cheers to you",
        price: "0.02 ETH",
      },
    ],
  },

  sorry: {
    title: "Apology Cards",
    subtitle: "Make amends with sincere apologies.",
    cards: [
      {
        id: "sorry-1",
        title: "I'm Sorry",
        byline: "by Everlink",
        tags: ["#sorry", "#apology"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/sorry/sorry1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/sorry.svg",
        tapeText: "I'M SORRY",
        description: "A heartfelt apology",
        price: "0.02 ETH",
      },
      {
        id: "sorry-2",
        title: "My Mistake",
        byline: "by Everlink",
        tags: ["#sorry", "#mistake"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/sorry/sorry2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/sorry.svg",
        tapeText: "MY MISTAKE",
        description: "Taking responsibility",
        price: "0.02 ETH",
      },
      {
        id: "sorry-3",
        title: "Forgive Me",
        byline: "by Everlink",
        tags: ["#sorry", "#forgive"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/sorry/sorry3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/sorry.svg",
        tapeText: "FORGIVE ME",
        description: "Please forgive me",
        price: "0.02 ETH",
      },
      {
        id: "sorry-4",
        title: "Oops",
        byline: "by Everlink",
        tags: ["#sorry", "#oops"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/sorry/sorry4.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/sorry.svg",
        tapeText: "OOPS!",
        description: "Oops, my bad",
        price: "0.02 ETH",
      },
      {
        id: "sorry-5",
        title: "Making Amends",
        byline: "by Everlink",
        tags: ["#sorry", "#amends"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/sorry/sorry5.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/sorry.svg",
        tapeText: "MAKING AMENDS",
        description: "Making things right",
        price: "0.02 ETH",
      },
    ],
  },

  situation: {
    title: "Situationship Cards",
    subtitle: "Navigate complex relationships with care.",
    cards: [
      {
        id: "situation-1",
        title: "It's Complicated",
        byline: "by Everlink",
        tags: ["#situationship", "#complicated"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "IT'S COMPLICATED",
        description: "When things are complex",
        price: "0.02 ETH",
      },
      {
        id: "situation-2",
        title: "Mixed Signals",
        byline: "by Everlink",
        tags: ["#situationship", "#mixed"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "MIXED SIGNALS",
        description: "Navigating unclear waters",
        price: "0.02 ETH",
      },
      {
        id: "situation-3",
        title: "Undefined",
        byline: "by Everlink",
        tags: ["#situationship", "#undefined"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "UNDEFINED",
        description: "No labels needed",
        price: "0.02 ETH",
      },
      {
        id: "situation-4",
        title: "What Are We",
        byline: "by Everlink",
        tags: ["#situationship", "#what"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship4.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "WHAT ARE WE?",
        description: "The age old question",
        price: "0.02 ETH",
      },
      {
        id: "situation-5",
        title: "Vibes Only",
        byline: "by Everlink",
        tags: ["#situationship", "#vibes"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship5.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "VIBES ONLY",
        description: "Just vibes",
        price: "0.02 ETH",
      },
      {
        id: "situation-6",
        title: "No Strings",
        byline: "by Everlink",
        tags: ["#situationship", "#nostrings"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship6.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "NO STRINGS",
        description: "No strings attached",
        price: "0.02 ETH",
      },
      {
        id: "situation-7",
        title: "Talking Stage",
        byline: "by Everlink",
        tags: ["#situationship", "#talking"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship7.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "TALKING STAGE",
        description: "Still in the talking stage",
        price: "0.02 ETH",
      },
      {
        id: "situation-8",
        title: "Maybe",
        byline: "by Everlink",
        tags: ["#situationship", "#maybe"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship8.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "MAYBE?",
        description: "Maybe, maybe not",
        price: "0.02 ETH",
      },
      {
        id: "situation-9",
        title: "On & Off",
        byline: "by Everlink",
        tags: ["#situationship", "#onoff"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship9.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "ON & OFF",
        description: "The on and off cycle",
        price: "0.02 ETH",
      },
      {
        id: "situation-10",
        title: "DTR",
        byline: "by Everlink",
        tags: ["#situationship", "#dtr"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/situationship/situationship10.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/situation.svg",
        tapeText: "DEFINE THE RELATIONSHIP",
        description: "Time to DTR",
        price: "0.02 ETH",
      },
    ],
  },

  friendship: {
    title: "Friendship Cards",
    subtitle: "Celebrate the bonds of friendship.",
    cards: [
      {
        id: "friendship-1",
        title: "Best Friends",
        byline: "by Everlink",
        tags: ["#friendship", "#bff"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/friendship/friendship1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/friends.svg",
        tapeText: "BEST FRIENDS!",
        description: "Celebrate true friendship",
        price: "0.02 ETH",
      },
      {
        id: "friendship-2",
        title: "Squad Goals",
        byline: "by Everlink",
        tags: ["#friendship", "#squad"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/friendship/friendship2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/friends.svg",
        tapeText: "SQUAD GOALS!",
        description: "Friendship squad celebration",
        price: "0.02 ETH",
      },
      {
        id: "friendship-3",
        title: "Ride or Die",
        byline: "by Everlink",
        tags: ["#friendship", "#rideordie"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/friendship/friendship3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/friends.svg",
        tapeText: "RIDE OR DIE!",
        description: "Through thick and thin",
        price: "0.02 ETH",
      },
      {
        id: "friendship-4",
        title: "Fren",
        byline: "by Everlink",
        tags: ["#friendship", "#fren"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/friendship/friendship4.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/friends.svg",
        tapeText: "GM FREN!",
        description: "gm fren, have a great day",
        price: "0.02 ETH",
      },
      {
        id: "friendship-5",
        title: "Bros",
        byline: "by Everlink",
        tags: ["#friendship", "#bros"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/friendship/friendship5.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/friends.svg",
        tapeText: "BROS!",
        description: "Bros forever",
        price: "0.02 ETH",
      },
      {
        id: "friendship-6",
        title: "Besties",
        byline: "by Everlink",
        tags: ["#friendship", "#besties"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/friendship/friendship6.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/friends.svg",
        tapeText: "BESTIES!",
        description: "Besties for life",
        price: "0.02 ETH",
      },
      {
        id: "friendship-7",
        title: "Day Ones",
        byline: "by Everlink",
        tags: ["#friendship", "#dayones"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/friendship/friendship7.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/friends.svg",
        tapeText: "DAY ONES!",
        description: "From day one",
        price: "0.02 ETH",
      },
    ],
  },

  degen: {
    title: "Degen Cards",
    subtitle: "For the crypto enthusiasts and risk-takers.",
    cards: [
      {
        id: "degen-1",
        title: "Degen Vibes",
        byline: "by Everlink",
        tags: ["#degen", "#crypto"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/degen/degen1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/degen.svg",
        tapeText: "DEGEN VIBES!",
        description: "For the crypto degenerates",
        price: "0.02 ETH",
      },
      {
        id: "degen-2",
        title: "To The Moon",
        byline: "by Everlink",
        tags: ["#degen", "#moon"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/degen/degen2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/degen.svg",
        tapeText: "TO THE MOON!",
        description: "Crypto moon mission",
        price: "0.02 ETH",
      },
      {
        id: "degen-3",
        title: "WAGMI",
        byline: "by Everlink",
        tags: ["#degen", "#wagmi"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/degen/degen3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/degen.svg",
        tapeText: "WAGMI!",
        description: "We're all gonna make it",
        price: "0.02 ETH",
      },
      {
        id: "degen-4",
        title: "Diamond Hands",
        byline: "by Everlink",
        tags: ["#degen", "#diamondhands"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/degen/degen4.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/degen.svg",
        tapeText: "DIAMOND HANDS!",
        description: "Hold the line",
        price: "0.02 ETH",
      },
      {
        id: "degen-5",
        title: "Ape In",
        byline: "by Everlink",
        tags: ["#degen", "#ape"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/degen/degen5.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/degen.svg",
        tapeText: "APE IN!",
        description: "Full send",
        price: "0.02 ETH",
      },
      {
        id: "degen-6",
        title: "HODL",
        byline: "by Everlink",
        tags: ["#degen", "#hodl"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/degen/degen6.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/degen.svg",
        tapeText: "HODL!",
        description: "Hold on for dear life",
        price: "0.02 ETH",
      },
      {
        id: "degen-7",
        title: "Bullish",
        byline: "by Everlink",
        tags: ["#degen", "#bullish"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/degen/degen7.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/degen.svg",
        tapeText: "BULLISH!",
        description: "Extremely bullish",
        price: "0.02 ETH",
      },
    ],
  },

  motivational: {
    title: "Motivational Cards",
    subtitle: "Inspire and uplift with positive messages.",
    cards: [
      {
        id: "motivational-1",
        title: "Rise & Shine",
        byline: "by Everlink",
        tags: ["#motivation", "#inspiration"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/motivational/motivational1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/motivation.svg",
        tapeText: "RISE & SHINE!",
        description: "Start your day with motivation",
        price: "0.02 ETH",
      },
      {
        id: "motivational-2",
        title: "Never Give Up",
        byline: "by Everlink",
        tags: ["#motivation", "#perseverance"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/motivational/motivational2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/motivation.svg",
        tapeText: "NEVER GIVE UP!",
        description: "Keep pushing forward",
        price: "0.02 ETH",
      },
      {
        id: "motivational-3",
        title: "You Got This",
        byline: "by Everlink",
        tags: ["#motivation", "#believe"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/motivational/motivational3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/motivation.svg",
        tapeText: "YOU GOT THIS!",
        description: "Believe in yourself",
        price: "0.02 ETH",
      },
      {
        id: "motivational-4",
        title: "Keep Going",
        byline: "by Everlink",
        tags: ["#motivation", "#strength"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/motivational/motivational4.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/motivation.svg",
        tapeText: "KEEP GOING!",
        description: "Stay strong and keep going",
        price: "0.02 ETH",
      },
    ],
  },

  base: {
    title: "Base Ecosystem Cards",
    subtitle: "Celebrate the Base blockchain community.",
    cards: [
      {
        id: "base-1",
        title: "Base Builder",
        byline: "by Everlink",
        tags: ["#base", "#ecosystem"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/base/base1.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/base.svg",
        tapeText: "BASE BUILDER!",
        description: "Building on Base",
        price: "0.02 ETH",
      },
      {
        id: "base-2",
        title: "Onchain Life",
        byline: "by Everlink",
        tags: ["#base", "#onchain"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/base/base2.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/base.svg",
        tapeText: "ONCHAIN LIFE!",
        description: "Living on the blockchain",
        price: "0.02 ETH",
      },
      {
        id: "base-3",
        title: "Based",
        byline: "by Everlink",
        tags: ["#base", "#based"],
        likes: 0,
        cta: "Choose Card",
        paperImage: "/images/categories/base/base3.png",
        overlayImage: "/images/loffy.png",
        brandIcon: "/images/base.svg",
        tapeText: "BASED!",
        description: "Extremely based",
        price: "0.02 ETH",
      },
    ],
  },
};

// Helper functions
export function getCategoryData(category: string): CategoryData | null {
  return greetingCardsData[category] || null;
}

export function getAllCategories(): string[] {
  return Object.keys(greetingCardsData);
}

export function getCardData(
  category: string,
  cardId: string
): GreetingCardData | null {
  const categoryData = getCategoryData(category);
  if (!categoryData) return null;
  return categoryData.cards.find((card) => card.id === cardId) || null;
}

// Get all cards across all categories (follows categoryMeta order so Miggles shows first)
export function getAllCards(): GreetingCardData[] {
  const ordered: GreetingCardData[] = [];
  for (const meta of categoryMeta) {
    const cat = greetingCardsData[meta.key];
    if (cat) ordered.push(...cat.cards);
  }
  // Append any categories not in categoryMeta
  for (const [key, cat] of Object.entries(greetingCardsData)) {
    if (!categoryMeta.some((m) => m.key === key)) {
      ordered.push(...cat.cards);
    }
  }
  return ordered;
}
